apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-app-backend
  namespace: fusion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fusion-app-backend
  template:
    metadata:
      labels:
        name: fusion-app-backend
    spec:
      serviceAccountName: fusion-app
      containers:
        - name: fusion-app
          # Replace this with the built image name
          image: registry.cn-hangzhou.aliyuncs.com/njuicscn/fusion-app-backend:201911281401
          command:
            - /usr/local/bin/fusionapp-dashboard
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fusion-app"
