apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resources.fusionapp.io
spec:
  group: fusionapp.io
  names:
    kind: Resource
    listKind: ResourceList
    plural: resources
    singular: resource
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
