apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-app-operator
  namespace: fusion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fusion-app
  template:
    metadata:
      labels:
        name: fusion-app
    spec:
      serviceAccountName: fusion-app
      containers:
        - name: fusion-app
          # Replace this with the built image name
          image: registry.cn-hangzhou.aliyuncs.com/njuicscn/fusion-app-operator:202010291322
          command:
          - /usr/local/bin/fusionapp-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1500m
              memory: 1Gi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fusion-app"
            - name: MQ_ADRESS
              value: "221.228.66.83:30595"
            - name: RESOURCE_PROBE_ENABLED
              value: "true"
            - name: APPINSTANCE_PROBE_ENABLED
              value: "true"
            - name: APPINSTANCE_PROBE_IMAGE
              value: "registry.cn-shanghai.aliyuncs.com/fusion-app/http-prober:instance-prober.201911300110"
            - name: APPINSTANCE_HTTP_URL
              value: "https://app-engine.2018yfb1004800.cn:30081/get_app_instance_action_state_and_resource_by_uid"
