kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fusion-app
subjects:
- kind: ServiceAccount
  name: fusion-app
  namespace: fusion-app
- kind: ServiceAccount
  name: fusion-app
  namespace: fusion-app-resources
roleRef:
  kind: ClusterRole
  name: fusion-app
  apiGroup: rbac.authorization.k8s.io
