kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fusion-app
subjects:
- kind: ServiceAccount
  name: fusion-app
roleRef:
  kind: Role
  name: fusion-app
  apiGroup: rbac.authorization.k8s.io
