apiVersion: v1
kind: Service
metadata:
  name: fusion-app-backend
  namespace: fusion-app
spec:
  ports:
    - name: http
      nodePort: 32022
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    name: fusion-app-backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: message-broker
  namespace: fusion-app
spec:
  ports:
    - port: 8082
      name: http
      targetPort: http
  selector:
    name: message-broker
  type: ClusterIP