apiVersion: v1
kind: Service
metadata:
  name: fusion-app-backend
  namespace: fusion-app
spec:
  ports:
    - name: http
      nodePort: 32022
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    name: fusion-app-backend
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-app-watcher
  namespace: fusion-app
spec:
  ports:
    - name: socket
      nodePort: 32023
      port: 8081
      protocol: TCP
      targetPort: socket
  selector:
    name: fusion-app-backend
  type: NodePort