// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.Resource":       schema_pkg_apis_fusionapp_v1alpha1_Resource(ref),
		"github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceSpec":   schema_pkg_apis_fusionapp_v1alpha1_ResourceSpec(ref),
		"github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceStatus": schema_pkg_apis_fusionapp_v1alpha1_ResourceStatus(ref),
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_Resource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Resource is the Schema for the resources API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceSpec", "github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceSpec defines the desired state of Resource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceStatus defines the observed state of Resource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
