/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/fusion-app/fusion-app/pkg/apis/fusionapp/v1alpha1"
	scheme "github.com/fusion-app/fusion-app/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FusionAppInstancesGetter has a method to return a FusionAppInstanceInterface.
// A group's client should implement this interface.
type FusionAppInstancesGetter interface {
	FusionAppInstances(namespace string) FusionAppInstanceInterface
}

// FusionAppInstanceInterface has methods to work with FusionAppInstance resources.
type FusionAppInstanceInterface interface {
	Create(*v1alpha1.FusionAppInstance) (*v1alpha1.FusionAppInstance, error)
	Update(*v1alpha1.FusionAppInstance) (*v1alpha1.FusionAppInstance, error)
	UpdateStatus(*v1alpha1.FusionAppInstance) (*v1alpha1.FusionAppInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FusionAppInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.FusionAppInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FusionAppInstance, err error)
	FusionAppInstanceExpansion
}

// fusionAppInstances implements FusionAppInstanceInterface
type fusionAppInstances struct {
	client rest.Interface
	ns     string
}

// newFusionAppInstances returns a FusionAppInstances
func newFusionAppInstances(c *FusionappV1alpha1Client, namespace string) *fusionAppInstances {
	return &fusionAppInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fusionAppInstance, and returns the corresponding fusionAppInstance object, and an error if there is any.
func (c *fusionAppInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.FusionAppInstance, err error) {
	result = &v1alpha1.FusionAppInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fusionappinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FusionAppInstances that match those selectors.
func (c *fusionAppInstances) List(opts v1.ListOptions) (result *v1alpha1.FusionAppInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FusionAppInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fusionappinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fusionAppInstances.
func (c *fusionAppInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fusionappinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a fusionAppInstance and creates it.  Returns the server's representation of the fusionAppInstance, and an error, if there is any.
func (c *fusionAppInstances) Create(fusionAppInstance *v1alpha1.FusionAppInstance) (result *v1alpha1.FusionAppInstance, err error) {
	result = &v1alpha1.FusionAppInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fusionappinstances").
		Body(fusionAppInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a fusionAppInstance and updates it. Returns the server's representation of the fusionAppInstance, and an error, if there is any.
func (c *fusionAppInstances) Update(fusionAppInstance *v1alpha1.FusionAppInstance) (result *v1alpha1.FusionAppInstance, err error) {
	result = &v1alpha1.FusionAppInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fusionappinstances").
		Name(fusionAppInstance.Name).
		Body(fusionAppInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *fusionAppInstances) UpdateStatus(fusionAppInstance *v1alpha1.FusionAppInstance) (result *v1alpha1.FusionAppInstance, err error) {
	result = &v1alpha1.FusionAppInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fusionappinstances").
		Name(fusionAppInstance.Name).
		SubResource("status").
		Body(fusionAppInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the fusionAppInstance and deletes it. Returns an error if one occurs.
func (c *fusionAppInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fusionappinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fusionAppInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fusionappinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched fusionAppInstance.
func (c *fusionAppInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FusionAppInstance, err error) {
	result = &v1alpha1.FusionAppInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fusionappinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
